services:
  postgres:
    image: postgres:16-alpine
    container_name: phongtzzz_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: phongtzzz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - phongtzzz_pgdata:/var/lib/postgresql/data

volumes:
  phongtzzz_pgdata:
