"use client"

import type React from "react"
import { useEffect, useState } from "react"
import { ArrowDown, ArrowUp, Edit, Plus, Save, Trash } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { MediaPicker, type MediaPickerItem } from "@/media-picker"

const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api"
const PUBLIC_SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:5173").replace(/\/$/, "")

type MediaItem = MediaPickerItem & { role?: "hero" | "gallery" | "itinerary" }
type TourOption = { value: string; label: string; description?: string; price_modifier?: number; currency?: string; recommended?: boolean }
type TourDay = { id?: string; day_number: number; title: string; description?: string | null; stops: string[] }
type Tour = { id: string; slug: string; name: string; tagline?: string | null; short_description?: string | null; description?: string | null; duration_days: number; duration_nights: number; price: number; currency: string; highlights: string[]; inclusions: string[]; exclusions: string[]; riding_options: TourOption[]; bus_options: TourOption[]; faq: Array<{ question: string; answer: string }>; itinerary: TourDay[]; media: MediaItem[]; is_featured: boolean; is_active: boolean; sort_order: number }
type TourAddon = { id: string; code: string; name: string; description?: string | null; price: number; currency: string; unit_label?: string | null; is_active: boolean; sort_order: number }
type TourPage = Record<string, any>
type TourForm = { id?: string; name: string; slug: string; tagline: string; short_description: string; description: string; duration_days: string; duration_nights: string; price: string; currency: string; highlights: string; inclusions: string; exclusions: string; riding_options: string; bus_options: string; faq: string; itinerary: string; media: MediaItem[]; is_featured: boolean; is_active: boolean; sort_order: string }

const emptyTour: TourForm = { name: "", slug: "", tagline: "", short_description: "", description: "", duration_days: "3", duration_nights: "2", price: "150", currency: "USD", highlights: "", inclusions: "", exclusions: "", riding_options: "easy-rider | Easy-Rider | Ride with an experienced local driver. | 0 | USD | yes\nself-driving | Self-Driving | Ride your own motorbike. | 0 | USD | no", bus_options: "hanoi-round-trip | Round-trip VIP cabin bus Hanoi ↔ Ha Giang | Included in the package. | 0 | USD\nself-arranged | I will arrange my own transport | Meet us in Ha Giang. | 0 | USD", faq: "", itinerary: "", media: [], is_featured: false, is_active: true, sort_order: "0" }

function token() { return typeof window === "undefined" ? "" : localStorage.getItem("riverside_admin_token") || "" }
function displayUrl(item?: MediaItem | null) { const url = item?.url || ""; if (!url || /^(https?:|data:|blob:)/i.test(url)) return url; return `${PUBLIC_SITE_URL}${url.startsWith("/") ? "" : "/"}${url}` }
function list(value: string) { return value.split("\n").flatMap((line) => line.split(",")).map((v) => v.trim()).filter(Boolean) }
function join(value?: string[]) { return (value || []).join("\n") }
function optionsFromText(value: string, recommended = false): TourOption[] { return value.split("\n").map((line) => line.trim()).filter(Boolean).map((line) => { const [v, label, description, mod, currency, rec] = line.split("|").map((x) => x.trim()); return { value: v, label: label || v, description: description || "", price_modifier: Number(mod || 0), currency: currency || "USD", recommended: recommended ? /^(yes|true|1)$/i.test(rec || "") : undefined } }) }
function optionsText(value?: TourOption[], recommended = false) { return (value || []).map((o) => [o.value, o.label, o.description || "", o.price_modifier || 0, o.currency || "USD", ...(recommended ? [o.recommended ? "yes" : "no"] : [])].join(" | ")).join("\n") }
function faqFromText(value: string) { return value.split("\n").map((line) => line.trim()).filter(Boolean).map((line) => { const [question, ...answer] = line.split("|").map((x) => x.trim()); return { question, answer: answer.join(" | ") } }).filter((x) => x.question && x.answer) }
function faqText(value?: Array<{ question: string; answer: string }>) { return (value || []).map((x) => `${x.question} | ${x.answer}`).join("\n") }
function itineraryFromText(value: string): TourDay[] { return value.split("\n").map((line) => line.trim()).filter(Boolean).map((line, index) => { const [dayRaw, title, description, stops] = line.split("|").map((x) => x.trim()); return { day_number: Number(dayRaw || index + 1), title: title || `Day ${index + 1}`, description: description || "", stops: (stops || "").split(",").map((x) => x.trim()).filter(Boolean) } }) }
function itineraryText(value?: TourDay[]) { return (value || []).map((x) => `${x.day_number} | ${x.title} | ${x.description || ""} | ${(x.stops || []).join(", ")}`).join("\n") }
function pageReviewsText(value?: Array<any>) { return (value || []).map((x) => `${x.name || ""} | ${x.country || ""} | ${x.rating || 5} | ${x.text || ""}`).join("\n") }
function reviewsFromText(value: string) { return value.split("\n").map((line) => line.trim()).filter(Boolean).map((line) => { const [name, country, rating, ...text] = line.split("|").map((x) => x.trim()); return { name, country, rating: Number(rating || 5), text: text.join(" | ") } }) }
function whyText(value?: Array<any>) { return (value || []).map((x) => `${x.title || ""} | ${x.description || ""}`).join("\n") }
function whyFromText(value: string) { return value.split("\n").map((line) => line.trim()).filter(Boolean).map((line) => { const [title, ...description] = line.split("|").map((x) => x.trim()); return { title, description: description.join(" | ") } }) }
function move<T extends { sort_order?: number }>(items: T[], from: number, to: number) { if (to < 0 || to >= items.length) return items; const arr = [...items]; const [item] = arr.splice(from, 1); arr.splice(to, 0, item); return arr.map((x, i) => ({ ...x, sort_order: i })) }

async function request<T>(path: string, options?: RequestInit): Promise<T> {
  const response = await fetch(`${API_URL}${path}`, { cache: "no-store", ...options, headers: { ...(options?.body instanceof FormData ? {} : { "Content-Type": "application/json" }), Authorization: `Bearer ${token()}`, ...(options?.headers || {}) } })
  if (!response.ok) { let detail = response.statusText; try { const data = await response.json(); detail = typeof data.detail === "string" ? data.detail : JSON.stringify(data.detail) } catch {} throw new Error(detail) }
  if (response.status === 204) return undefined as T
  return response.json()
}

function tourToForm(t: Tour): TourForm { return { id: t.id, name: t.name, slug: t.slug, tagline: t.tagline || "", short_description: t.short_description || "", description: t.description || "", duration_days: String(t.duration_days), duration_nights: String(t.duration_nights), price: String(t.price), currency: t.currency, highlights: join(t.highlights), inclusions: join(t.inclusions), exclusions: join(t.exclusions), riding_options: optionsText(t.riding_options, true), bus_options: optionsText(t.bus_options), faq: faqText(t.faq), itinerary: itineraryText(t.itinerary), media: [...(t.media || [])].sort((a, b) => (a.sort_order || 0) - (b.sort_order || 0)), is_featured: t.is_featured, is_active: t.is_active, sort_order: String(t.sort_order) } }
function tourPayload(f: TourForm) { return { name: f.name, slug: f.slug || undefined, tagline: f.tagline || null, short_description: f.short_description || null, description: f.description || null, duration_days: Number(f.duration_days || 1), duration_nights: Number(f.duration_nights || 0), price: Number(f.price || 0), currency: f.currency || "USD", highlights: list(f.highlights), inclusions: list(f.inclusions), exclusions: list(f.exclusions), riding_options: optionsFromText(f.riding_options, true), bus_options: optionsFromText(f.bus_options), faq: faqFromText(f.faq), itinerary: itineraryFromText(f.itinerary), media: f.media.map((m, index) => ({ ...m, role: m.role || "gallery", sort_order: index })), is_featured: f.is_featured, is_active: f.is_active, sort_order: Number(f.sort_order || 0) } }

export function ToursAdminPanel() {
  const [tours, setTours] = useState<Tour[]>([])
  const [addons, setAddons] = useState<TourAddon[]>([])
  const [page, setPage] = useState<TourPage>({})
  const [form, setForm] = useState<TourForm>(emptyTour)
  const [message, setMessage] = useState("")
  const [error, setError] = useState("")
  const [addonDraft, setAddonDraft] = useState({ code: "", name: "", description: "", price: "0", currency: "VND", unit_label: "", sort_order: "0" })

  async function load() { try { const [tourData, pageData, addonData] = await Promise.all([request<Tour[]>("/admin/tours"), request<{ value: TourPage }>("/admin/tour-page"), request<TourAddon[]>("/admin/tour-addons")]); setTours(tourData); setPage(pageData.value || {}); setAddons(addonData); setError("") } catch (e) { setError(e instanceof Error ? e.message : "Could not load tours") } }
  useEffect(() => { void load() }, [])
  useEffect(() => { if (!message && !error) return; const timer = window.setTimeout(() => { setMessage(""); setError("") }, error ? 5500 : 3500); return () => window.clearTimeout(timer) }, [message, error])

  const set = (key: keyof TourForm, value: any) => setForm((prev) => ({ ...prev, [key]: value }))
  async function saveTour(event: React.FormEvent) { event.preventDefault(); try { if (form.id) await request(`/admin/tours/${form.id}`, { method: "PATCH", body: JSON.stringify(tourPayload(form)) }); else await request("/admin/tours", { method: "POST", body: JSON.stringify(tourPayload(form)) }); setMessage(form.id ? "Tour saved" : "Tour created"); setForm(emptyTour); await load() } catch (e) { setError(e instanceof Error ? e.message : "Could not save tour") } }
  async function deleteTour(id: string) { if (!confirm("Delete this tour? Existing booking requests keep their tour snapshot.")) return; try { await request(`/admin/tours/${id}`, { method: "DELETE" }); if (form.id === id) setForm(emptyTour); setMessage("Tour deleted"); await load() } catch (e) { setError(e instanceof Error ? e.message : "Could not delete tour") } }
  async function savePage() { try { await request("/admin/tour-page", { method: "PUT", body: JSON.stringify({ value: page }) }); setMessage("Tours overview saved"); await load() } catch (e) { setError(e instanceof Error ? e.message : "Could not save tour page") } }
  async function createAddon() { try { await request("/admin/tour-addons", { method: "POST", body: JSON.stringify({ ...addonDraft, price: Number(addonDraft.price || 0), sort_order: Number(addonDraft.sort_order || 0), is_active: true }) }); setAddonDraft({ code: "", name: "", description: "", price: "0", currency: "VND", unit_label: "", sort_order: "0" }); setMessage("Add-on created"); await load() } catch (e) { setError(e instanceof Error ? e.message : "Could not add add-on") } }
  async function updateAddon(id: string, patch: Partial<TourAddon>) { try { await request(`/admin/tour-addons/${id}`, { method: "PATCH", body: JSON.stringify(patch) }); await load() } catch (e) { setError(e instanceof Error ? e.message : "Could not update add-on") } }
  async function deleteAddon(id: string) { if (!confirm("Delete this add-on? Existing requests keep their add-on snapshot.")) return; await request(`/admin/tour-addons/${id}`, { method: "DELETE" }); await load() }

  const selectTourMedia = (items: MediaPickerItem[]) => setForm((prev) => {
    const oldRole = new Map(prev.media.map((m) => [m.asset_id || m.url, m.role]))
    return { ...prev, media: items.map((item, index) => ({ ...item, role: oldRole.get(item.asset_id || item.url) || (index === 0 && !prev.media.length ? "hero" : "gallery"), sort_order: index })) }
  })
  const replaceTourMedia = (index: number, media: MediaPickerItem) => setForm((prev) => ({ ...prev, media: prev.media.map((item, i) => i === index ? { ...media, role: item.role || "gallery", sort_order: i } : item) }))

  return <div className="space-y-5">
    {(message || error) ? <div className={`fixed right-5 top-5 z-[310] max-w-md rounded-xl border px-4 py-3 text-sm shadow-xl ${error ? "border-red-200 bg-red-50 text-red-700" : "border-green-200 bg-green-50 text-green-700"}`}>{error || message}</div> : null}

    <Card><CardHeader><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><CardTitle>Tour Overview Page</CardTitle><CardDescription>Public /tours. Media được chọn từ thư viện chung và có thể tái sử dụng.</CardDescription></div><Button onClick={() => void savePage()}><Save size={15} className="mr-2" />Save Tours Page</Button></div></CardHeader><CardContent className="space-y-4">
      <div className="grid gap-4 md:grid-cols-2"><Field label="Hero title"><Input value={page.heroTitle || ""} onChange={(e) => setPage({ ...page, heroTitle: e.target.value })} /></Field><Field label="Hero slogan"><Input value={page.heroSlogan || ""} onChange={(e) => setPage({ ...page, heroSlogan: e.target.value })} /></Field><Field label="Packages title"><Input value={page.packagesTitle || ""} onChange={(e) => setPage({ ...page, packagesTitle: e.target.value })} /></Field><Field label="Book button text"><Input value={page.bookingButtonText || ""} onChange={(e) => setPage({ ...page, bookingButtonText: e.target.value })} /></Field></div>
      <Field label="Hero description"><Textarea value={page.heroDescription || ""} onChange={(e) => setPage({ ...page, heroDescription: e.target.value })} /></Field>
      <div className="grid gap-4 lg:grid-cols-2"><div className="rounded-lg border bg-gray-50 p-3"><p className="mb-2 text-sm font-semibold">Tours hero image</p><MediaPicker label="Chọn ảnh" accept="image" selected={page.heroImage ? [page.heroImage] : []} onSelect={(items) => setPage((p: any) => ({ ...p, heroImage: items[0] || null }))} />{page.heroImage ? <SimpleMediaGrid items={[page.heroImage]} onRemove={() => setPage({ ...page, heroImage: null })} onReplace={(_, media) => setPage((p: any) => ({ ...p, heroImage: media }))} /> : null}</div><div className="rounded-lg border bg-gray-50 p-3"><p className="mb-2 text-sm font-semibold">Tours social/gallery images</p><MediaPicker label="Chọn ảnh" multiple accept="image" selected={page.gallery || []} onSelect={(items) => setPage((p: any) => ({ ...p, gallery: items.map((x, i) => ({ ...x, sort_order: i })) }))} /><SimpleMediaGrid items={page.gallery || []} onMove={(from, to) => setPage((p: any) => ({ ...p, gallery: move((p.gallery || []), from, to) }))} onRemove={(index) => setPage((p: any) => ({ ...p, gallery: (p.gallery || []).filter((_: any, i: number) => i !== index).map((x: any, i: number) => ({ ...x, sort_order: i })) }))} onReplace={(index, media) => setPage((p: any) => ({ ...p, gallery: (p.gallery || []).map((x: any, i: number) => i === index ? { ...media, sort_order: i } : x) }))} /></div></div>
      <div className="grid gap-4 md:grid-cols-2"><Field label="What's Included — one line/item"><Textarea rows={7} value={join(page.includedItems)} onChange={(e) => setPage({ ...page, includedItems: list(e.target.value) })} /></Field><Field label="Why items — Title | Description"><Textarea rows={7} value={whyText(page.whyItems)} onChange={(e) => setPage({ ...page, whyItems: whyFromText(e.target.value) })} /></Field><Field label="Reviews — Name | Country | Rating | Text"><Textarea rows={7} value={pageReviewsText(page.reviews)} onChange={(e) => setPage({ ...page, reviews: reviewsFromText(e.target.value) })} /></Field><Field label="FAQ — Question | Answer"><Textarea rows={7} value={faqText(page.faq)} onChange={(e) => setPage({ ...page, faq: faqFromText(e.target.value) })} /></Field></div>
      <div className="grid gap-4 md:grid-cols-3"><Field label="Included title"><Input value={page.includedTitle || ""} onChange={(e) => setPage({ ...page, includedTitle: e.target.value })} /></Field><Field label="Why title"><Input value={page.whyTitle || ""} onChange={(e) => setPage({ ...page, whyTitle: e.target.value })} /></Field><Field label="Gallery title"><Input value={page.galleryTitle || ""} onChange={(e) => setPage({ ...page, galleryTitle: e.target.value })} /></Field><Field label="Reviews title"><Input value={page.reviewsTitle || ""} onChange={(e) => setPage({ ...page, reviewsTitle: e.target.value })} /></Field><Field label="FAQ title"><Input value={page.faqTitle || ""} onChange={(e) => setPage({ ...page, faqTitle: e.target.value })} /></Field></div>
      <Field label="Bottom booking CTA"><Input value={page.bookingTitle || ""} onChange={(e) => setPage({ ...page, bookingTitle: e.target.value })} /><Textarea className="mt-2" value={page.bookingDescription || ""} onChange={(e) => setPage({ ...page, bookingDescription: e.target.value })} /></Field>
    </CardContent></Card>

    <div className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]">
      <Card><CardHeader><CardTitle>{form.id ? `Edit: ${form.name}` : "Create Tour"}</CardTitle><CardDescription>Tour data, itinerary and media đều lưu DB.</CardDescription></CardHeader><CardContent><form onSubmit={saveTour} className="space-y-4">
        <div className="grid grid-cols-2 gap-3"><Field label="Name"><Input required value={form.name} onChange={(e) => set("name", e.target.value)} /></Field><Field label="Slug"><Input value={form.slug} onChange={(e) => set("slug", e.target.value)} /></Field></div><Field label="Tagline"><Input value={form.tagline} onChange={(e) => set("tagline", e.target.value)} /></Field><Field label="Short description"><Textarea value={form.short_description} onChange={(e) => set("short_description", e.target.value)} /></Field><Field label="Full description"><Textarea value={form.description} onChange={(e) => set("description", e.target.value)} /></Field>
        <div className="grid grid-cols-4 gap-2"><Field label="Days"><Input type="number" min="1" value={form.duration_days} onChange={(e) => set("duration_days", e.target.value)} /></Field><Field label="Nights"><Input type="number" min="0" value={form.duration_nights} onChange={(e) => set("duration_nights", e.target.value)} /></Field><Field label="Price"><Input type="number" min="0" value={form.price} onChange={(e) => set("price", e.target.value)} /></Field><Field label="Currency"><Input value={form.currency} onChange={(e) => set("currency", e.target.value.toUpperCase())} /></Field></div>
        <Field label="Highlights — one line/item"><Textarea rows={5} value={form.highlights} onChange={(e) => set("highlights", e.target.value)} /></Field><div className="grid gap-3 md:grid-cols-2"><Field label="Included"><Textarea rows={7} value={form.inclusions} onChange={(e) => set("inclusions", e.target.value)} /></Field><Field label="Not included"><Textarea rows={7} value={form.exclusions} onChange={(e) => set("exclusions", e.target.value)} /></Field></div><Field label="Itinerary — Day | Title | Description | stop1, stop2"><Textarea rows={8} value={form.itinerary} onChange={(e) => set("itinerary", e.target.value)} /></Field><Field label="Riding options — value | label | description | modifier | currency | recommended"><Textarea rows={6} value={form.riding_options} onChange={(e) => set("riding_options", e.target.value)} /></Field><Field label="Bus options — value | label | description | modifier | currency"><Textarea rows={5} value={form.bus_options} onChange={(e) => set("bus_options", e.target.value)} /></Field><Field label="FAQ — Question | Answer"><Textarea rows={5} value={form.faq} onChange={(e) => set("faq", e.target.value)} /></Field>
        <div className="rounded-lg border bg-gray-50 p-3"><p className="mb-1 text-sm font-semibold">Tour media</p><p className="mb-3 text-xs text-gray-500">Chọn ảnh/video đã có hoặc upload trong popup. Một asset có thể dùng cho nhiều tour.</p><MediaPicker label="Chọn media" multiple accept="all" selected={form.media} onSelect={selectTourMedia} /><SimpleMediaGrid items={form.media} showRole onMove={(from, to) => set("media", move(form.media, from, to))} onRemove={(index) => set("media", form.media.filter((_, i) => i !== index).map((x, i) => ({ ...x, sort_order: i })))} onReplace={replaceTourMedia} onRole={(index, role) => set("media", form.media.map((x, i) => i === index ? { ...x, role } : x))} /></div>
        <div className="grid grid-cols-3 gap-3"><Field label="Sort"><Input type="number" value={form.sort_order} onChange={(e) => set("sort_order", e.target.value)} /></Field><label className="flex items-center gap-2 pt-6 text-sm"><input type="checkbox" checked={form.is_featured} onChange={(e) => set("is_featured", e.target.checked)} /> Featured</label><label className="flex items-center gap-2 pt-6 text-sm"><input type="checkbox" checked={form.is_active} onChange={(e) => set("is_active", e.target.checked)} /> Public</label></div><div className="flex gap-2"><Button type="submit"><Save size={15} className="mr-2" />{form.id ? "Save Tour" : "Create Tour"}</Button>{form.id ? <Button type="button" variant="outline" onClick={() => setForm(emptyTour)}>Close</Button> : null}</div>
      </form></CardContent></Card>

      <Card><CardHeader><CardTitle>Tour packages</CardTitle><CardDescription>{tours.length} tour(s). Click Edit to load full itinerary/media.</CardDescription></CardHeader><CardContent><div className="space-y-3">{tours.map((tour) => <div key={tour.id} className="rounded-lg border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{tour.name}</p><p className="text-xs text-gray-500">{tour.duration_days}D{tour.duration_nights}N · {tour.price} {tour.currency} · {tour.media.length} media</p></div><span className={`rounded-full px-2 py-1 text-xs ${tour.is_active ? "bg-green-50 text-green-700" : "bg-gray-100 text-gray-500"}`}>{tour.is_active ? "Public" : "Hidden"}</span></div>{tour.media[0] ? <div className="mt-3 max-w-xs overflow-hidden rounded-md bg-gray-100" style={{ aspectRatio: "3/2" }}><img src={displayUrl(tour.media[0])} alt={tour.name} className="h-full w-full object-cover" /></div> : null}<div className="mt-3 flex gap-2"><Button size="sm" variant="outline" onClick={() => setForm(tourToForm(tour))}><Edit size={14} className="mr-1" />Edit</Button><Button size="sm" variant="ghost" onClick={() => void deleteTour(tour.id)}><Trash size={14} /></Button></div></div>)}</div></CardContent></Card>
    </div>

    <Card><CardHeader><CardTitle>Tour Add-ons</CardTitle><CardDescription>Optional services available in the unified room booking request.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-6"><Input placeholder="code" value={addonDraft.code} onChange={(e) => setAddonDraft({ ...addonDraft, code: e.target.value })} /><Input placeholder="Name" value={addonDraft.name} onChange={(e) => setAddonDraft({ ...addonDraft, name: e.target.value })} /><Input placeholder="Price" type="number" value={addonDraft.price} onChange={(e) => setAddonDraft({ ...addonDraft, price: e.target.value })} /><Input placeholder="Currency" value={addonDraft.currency} onChange={(e) => setAddonDraft({ ...addonDraft, currency: e.target.value.toUpperCase() })} /><Input placeholder="/ night" value={addonDraft.unit_label} onChange={(e) => setAddonDraft({ ...addonDraft, unit_label: e.target.value })} /><Button onClick={() => void createAddon()}><Plus size={14} className="mr-1" />Add</Button></div><Textarea placeholder="Description for new add-on" value={addonDraft.description} onChange={(e) => setAddonDraft({ ...addonDraft, description: e.target.value })} /><div className="space-y-3">{addons.map((addon) => <div key={addon.id} className="grid gap-3 rounded-lg border p-3 md:grid-cols-[1fr_120px_90px_120px_auto]"><div><Input defaultValue={addon.name} onBlur={(e) => void updateAddon(addon.id, { name: e.target.value })} /><Textarea className="mt-2 min-h-16" defaultValue={addon.description || ""} onBlur={(e) => void updateAddon(addon.id, { description: e.target.value })} /></div><Input type="number" defaultValue={addon.price} onBlur={(e) => void updateAddon(addon.id, { price: Number(e.target.value) })} /><Input defaultValue={addon.currency} onBlur={(e) => void updateAddon(addon.id, { currency: e.target.value.toUpperCase() })} /><Input defaultValue={addon.unit_label || ""} onBlur={(e) => void updateAddon(addon.id, { unit_label: e.target.value })} /><div className="flex items-start gap-2"><label className="flex items-center gap-1 text-xs"><input type="checkbox" checked={addon.is_active} onChange={(e) => void updateAddon(addon.id, { is_active: e.target.checked })} />Active</label><Button size="sm" variant="ghost" onClick={() => void deleteAddon(addon.id)}><Trash size={14} /></Button></div></div>)}</div></CardContent></Card>
  </div>
}

function SimpleMediaGrid({ items, onMove, onRemove, onReplace, showRole, onRole }: { items: MediaItem[]; onMove?: (from: number, to: number) => void; onRemove?: (index: number) => void; onReplace?: (index: number, media: MediaItem) => void | Promise<void>; showRole?: boolean; onRole?: (index: number, role: "hero" | "gallery" | "itinerary") => void }) {
  return <div className="mt-3 grid gap-3 sm:grid-cols-2">{items.map((item, index) => <div key={item.asset_id || `${item.url}-${index}`} className="rounded-lg border bg-white p-2"><div className="relative overflow-hidden rounded-md bg-gray-100" style={{ aspectRatio: "3/2" }}>{item.type === "video" ? <video src={displayUrl(item)} className="h-full w-full object-cover" muted /> : <img src={displayUrl(item)} alt={item.alt || item.original_filename || "media"} className="h-full w-full object-cover" />}<span className="absolute left-1 top-1 rounded bg-black/70 px-1.5 py-0.5 text-[10px] text-white">#{index + 1}</span></div><p className="mt-2 truncate text-xs" title={item.original_filename || item.storage_path || item.url}>{item.original_filename || item.storage_path || "media"}</p>{showRole ? <select className="mt-2 w-full rounded border px-2 py-1 text-xs" value={item.role || "gallery"} onChange={(e) => onRole?.(index, e.target.value as any)}><option value="hero">hero</option><option value="gallery">gallery</option><option value="itinerary">itinerary</option></select> : null}<div className="mt-2 flex flex-wrap gap-1"><Button type="button" size="sm" variant="outline" disabled={!onMove || index === 0} onClick={() => onMove?.(index, index - 1)}><ArrowUp size={12} /></Button><Button type="button" size="sm" variant="outline" disabled={!onMove || index === items.length - 1} onClick={() => onMove?.(index, index + 1)}><ArrowDown size={12} /></Button>{onReplace ? <MediaPicker label="Thay" accept={item.type === "video" ? "video" : "image"} selected={[item]} onSelect={(selected) => { if (selected[0]) void onReplace(index, selected[0]) }} /> : null}{onRemove ? <Button type="button" size="sm" variant="ghost" onClick={() => onRemove(index)}><Trash size={12} /></Button> : null}</div></div>)}</div>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block space-y-1"><span className="text-xs font-medium uppercase tracking-wide text-gray-500">{label}</span>{children}</label> }
