def media(url: str, media_type: str = 'image', sort_order: int = 0, alt: str | None = None) -> dict:
    return {'url': url, 'type': media_type, 'sort_order': sort_order, 'alt': alt or ''}


DEFAULT_LANDING_PAGE = {
    'brand': {
        'name': 'phongtzzz',
        'logoText': 'phongtzzz',
        'phone': '+84 983 393 954',
        'email': 'stayhostelbar@gmail.com',
        'address': 'Thon Coc Pang Km0, Du Gia, Ha Giang, Vietnam',
        'facebookUrl': '#',
        'instagramUrl': '#',
        'mapEmbedUrl': '',
        'logo': None,
    },
    'theme': {
        'fontFamily': 'Inter, Arial, sans-serif',
        'headingFont': 'Georgia, serif',
        'primaryColor': '#111111',
        'backgroundColor': '#f7f5f2',
    },
    'header': {
        'ctaText': 'Book Now',
        'ctaLink': '/contact',
        'navItems': [
            {'label': 'Home', 'path': '/'},
            {'label': 'Rooms', 'path': '/rooms'},
            {'label': 'Booking Request', 'path': '/contact'},
        ],
    },
    'footer': {
        'showCta': True,
        'bottomText': 'Booking request website',
        'quickLinksTitle': 'Quick links',
        'contactTitle': 'Contact Us',
        'socialTitle': 'Follow Us',
    },
    'contact': {
        'title': 'Send a booking request',
        'description': 'Tell us your travel dates. We will contact you to confirm room availability and complete the booking.',
        'successTitle': 'Request sent!',
        'successMessage': 'Thank you. Our homestay will contact you soon to confirm availability.',
    },
    'sections': [
        {
            'id': 'hero-main',
            'type': 'hero',
            'enabled': True,
            'sort_order': 1,
            'title': 'phongtzzz',
            'subtitle': 'Your sanctuary on the Ha Giang Loop. Where mountain serenity meets authentic local culture.',
            'primaryButtonText': 'Explore Rooms',
            'primaryButtonLink': '/rooms',
            'secondaryButtonText': 'Book Request',
            'secondaryButtonLink': '/contact',
            'video': media('/videos/hero-coast.mp4', 'video'),
            'image': None,
        },
        {
            'id': 'welcome-main',
            'type': 'welcome',
            'enabled': True,
            'sort_order': 2,
            'eyebrow': 'Welcome to phongtzzz',
            'title': 'A peaceful base for your Ha Giang journey',
            'paragraphs': [
                'Nestled among mountains and rice fields, phongtzzz is designed for travelers who want comfort, local culture and a slower pace after long riding days.',
                'Wake up to fresh air, share meals with new friends and let our team help you plan the next leg of your loop.',
            ],
            'images': [media('/images/gallery-landscape-1.jpg', sort_order=0), media('/images/gallery-guest-1.jpg', sort_order=1), media('/images/pool-area.jpg', sort_order=2)],
        },
        {
            'id': 'experiences-main',
            'type': 'experiences',
            'enabled': True,
            'sort_order': 3,
            'title': 'Experience Du Gia',
            'description': 'Discover local food, mountain routes, craft culture and quiet corners around the village.',
            'items': [
                {'title': 'Mountain Trekking', 'description': 'Guided walks through rice terraces, waterfalls and hidden viewpoints.', 'image': media('/images/trekking-path.jpg')},
                {'title': 'Local Dining', 'description': 'Home-style dinners and regional dishes prepared with local ingredients.', 'image': media('/images/food-dining.jpg')},
                {'title': 'Culture & Craft', 'description': 'Meet local families and learn about traditional weaving and village life.', 'image': media('/images/culture-weaving.jpg')},
            ],
        },
        {
            'id': 'rooms-main',
            'type': 'rooms',
            'enabled': True,
            'sort_order': 4,
            'title': 'Our Rooms',
            'description': 'From cozy dorms to private bungalows, find the perfect space for your mountain retreat.',
            'buttonText': 'View all rooms',
            'buttonLink': '/rooms',
            'limit': 3,
            'roomIds': [],
        },
        {
            'id': 'amenities-main',
            'type': 'amenities',
            'enabled': True,
            'sort_order': 5,
            'title': 'Everything You Need',
            'items': [
                {'title': 'Free WiFi', 'description': 'Stay connected throughout the property.'},
                {'title': 'Breakfast', 'description': 'Start the day with fresh local food.'},
                {'title': 'Motorbike Support', 'description': 'Route advice, parking and local help.'},
                {'title': 'Laundry', 'description': 'Simple laundry service for loop travelers.'},
            ],
        },
        {
            'id': 'testimonials-main',
            'type': 'testimonials',
            'enabled': True,
            'sort_order': 6,
            'title': 'Guest Stories',
            'items': [
                {'name': 'Mia', 'country': 'Australia', 'rating': 5, 'text': 'Beautiful location, kind staff and exactly what we needed after a long day riding.'},
                {'name': 'Lucas', 'country': 'Germany', 'rating': 5, 'text': 'The family dinner and mountain view made this one of our favorite stays in Vietnam.'},
            ],
        },
        {
            'id': 'gallery-main',
            'type': 'gallery',
            'enabled': True,
            'sort_order': 7,
            'title': 'Moments at phongtzzz',
            'images': [
                media('/images/gallery-dining.jpg', sort_order=0),
                media('/images/gallery-guest-1.jpg', sort_order=1),
                media('/images/gallery-guest-2.jpg', sort_order=2),
                media('/images/gallery-yoga.jpg', sort_order=3),
                media('/images/gallery-landscape-1.jpg', sort_order=4),
            ],
        },
        {
            'id': 'cta-main',
            'type': 'cta',
            'enabled': True,
            'sort_order': 8,
            'title': 'Ready for your mountain stay?',
            'description': 'Send a booking request and our team will get back to you as soon as possible.',
            'buttonText': 'Send Booking Request',
            'buttonLink': '/contact',
        },
    ],
}

DEFAULT_ROOMS = [
    {
        'name': 'Deluxe Double Room',
        'slug': 'deluxe-double-room',
        'type': 'private',
        'price': 450000,
        'original_price': 550000,
        'capacity': 2,
        'beds': 1,
        'bed_type': 'Queen bed',
        'size': '28 m²',
        'description': 'A spacious private room with a comfortable queen bed, mountain views and modern amenities.',
        'amenities': ['Free WiFi', 'Private bathroom', 'Mountain view', 'Breakfast included'],
        'highlights': ['Popular', 'Private'],
        'images': [media('/images/room-deluxe.jpg', sort_order=0), media('/images/pool-area.jpg', sort_order=1), media('/images/food-dining.jpg', sort_order=2)],
        'is_active': True,
        'sort_order': 1,
    },
    {
        'name': '4-Bed Dorm',
        'slug': '4-bed-dorm',
        'type': 'dorm',
        'price': 120000,
        'capacity': 4,
        'beds': 4,
        'bed_type': 'Bunk beds',
        'size': '32 m²',
        'description': 'A clean and social dorm room for budget travelers looking for comfort and community.',
        'amenities': ['Free WiFi', 'Shared bathroom', 'Locker', 'Breakfast available'],
        'highlights': ['Budget', 'Social'],
        'images': [media('/images/room-dorm.jpg', sort_order=0), media('/images/gallery-guest-1.jpg', sort_order=1)],
        'is_active': True,
        'sort_order': 2,
    },
    {
        'name': 'Mountain Bungalow',
        'slug': 'mountain-bungalow',
        'type': 'private',
        'price': 650000,
        'capacity': 2,
        'beds': 1,
        'bed_type': 'King bed',
        'size': '36 m²',
        'description': 'A standalone bungalow with a private balcony and peaceful views across the valley.',
        'amenities': ['Free WiFi', 'Private bathroom', 'Private balcony', 'Breakfast included'],
        'highlights': ['Best view', 'Private'],
        'images': [media('/images/room-bungalow.jpg', sort_order=0), media('/images/gallery-landscape-1.jpg', sort_order=1)],
        'is_active': True,
        'sort_order': 3,
    },
]
